apiVersion: v1
kind: Template
labels:
  template: kafka
metadata:
  name: kafka
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: kafka
  spec:
    ports:
    - name: kafka
      port: 9092
    - name: zookeeper
      port: 2181
    selector:
      name: kafka
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: kafka
  spec:
    replicas: 1
    selector:
      name: kafka
    template:
      metadata:
        name: kafka
        labels:
          name: kafka
      spec:
        containers:
        - name: kafka
          image: carbonin/kafka:latest
          command:
          - bin/kafka-server-start.sh
          args:
          - config/server.properties
          - --override
          - advertised.host.name=kafka
          - --override
          - log.segment.bytes=10485760
          - --override
          - log.retention.bytes=10485760
          volumeMounts:
          - mountPath: /tmp/kafka-logs
            name: kafka-logs
          ports:
          - containerPort: 9092
        - name: zookeeper
          image: carbonin/kafka:latest
          command:
          - bin/zookeeper-server-start.sh
          args:
          - config/zookeeper.properties
          volumeMounts:
          - mountPath: /tmp/zookeeper
            name: zookeeper
          ports:
          - containerPort: 2181
        volumes:
        - name: kafka-logs
          emptyDir: {}
        - name: zookeeper
          emptyDir: {}
